### ISSUE TITLE
Run BEFORE_ORTHANC_STARTUP_SCRIPT first thing in the ENTRYPOINT

### ISSUE THREAD

**Issue by andgineer** [orthanc-server/orthanc-builder#10]
Trying to fix https://github.com/orthanc-server/orthanc-builder/issues/9
I discovered that `BEFORE_ORTHANC_STARTUP_SCRIPT` is launched after config files processing.

So we cannot change configs in this script because they are already copied to cumulative config with
'secret' name `/tmp/orthanc.json` which is passed in CMD but is not accessible from `BEFORE_ORTHANC_STARTUP_SCRIPT`

May be we should
1) Launch the script as first thing
2) Do not hardcode  `/tmp/orthanc.json` in generateConfiguration.py but pass it to the python script as parameter
like `python3 generateConfiguration.py "$@"`

**Comment by amazy** [comment]
Some people might want to analyze the content of the generated config file at that time so we can not change it.  

We might define another custom script that would be called before the config file generation but don't forget anyone can have its own entrypoint/cmd as well so I don't think it is necessary.

**Comment by amazy** [comment]
/etc/orthanc is where you should put your configuration file as explained in the [documentation](https://book.orthanc-server.com/users/docker-osimis.html#configuration-files)
