### ISSUE TITLE
Specifying requirements in Python plugin config for non-standard libraries.

### ISSUE THREAD

**Issue by yomarbuzz** [orthanc-server/orthanc-builder#18]
Python plugin would greatly benefit from a feature that allows us to specify requirements.txt (or json list) in config that would be installed with pip when entrypoint is ran. Having to include all packages you need in CI or manually installing into running containers complicates python script development for Orthanc.

**Comment by amazy** [comment]
In my opinion, installation should be performed at build time and not at run time.
However, if you wish to perform a `pip install` at run time, you can still modify the docker entrypoint in your compose file.
