### ISSUE TITLE
Mismatch in the version of the Stone Web viewer

### ISSUE THREAD

**Issue by jodogne** [orthanc-server/orthanc-builder#5]
The Docker images don't use the correct version of the WebAssembly binaries. I guess this is because the `wasm-binaries.zip` are downloaded from the ["mainline" folder](https://lsb.orthanc-server.com/stone-webviewer/mainline/) instead of the ["2.4" folder](https://lsb.orthanc-server.com/stone-webviewer/2.4/). The same error is presumably also present in the Windows installers and macOS package (not tested).

![version](https://user-images.githubusercontent.com/6000889/199661128-a597c58f-d5c8-4c01-9e21-0a90726b1ce5.png)
![version-2](https://user-images.githubusercontent.com/6000889/199661131-143a0f5c-0a89-41ec-bf7e-362d060fd256.png)

**Comment by amazy** [comment]
trying to fix with this commit: https://github.com/orthanc-server/orthanc-builder/commit/270c028fee437c930c52a860f3d7a30cd7c833d0

**Comment by amazy** [comment]
fixed: 
![image](https://user-images.githubusercontent.com/14176104/199737725-259abbbc-c507-4c57-9aca-f70465844800.png)

Will be included in osimis/orthanc:22.11.1
