### ISSUE TITLE
CMake Error - arm64 local build

### ISSUE THREAD

**Issue by urosch** [orthanc-server/orthanc-builder#7]
I get error when trying to build local on arm64 raspberry pi:
`CMake Error at /opt/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake:131 (message):
Failed to fetch compiler version information with command
   "'/opt/emsdk/upstream/emscripten/emcc' -v"! Process returned with error
code Segmentation fault.
Call Stack (most recent call first):
  /tmp/build/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  /tmp/build/CMakeFiles/CMakeTmp/CMakeLists.txt:3 (project)
CMake Error at /usr/share/cmake-3.10/Modules/CheckFunctionExists.cmake:70 (try_compile):
Failed to configure test project build system.`

**Comment by urosch** [comment]
I ran build using the command:
`./local-build.sh version=stable platform=linux/arm64 image=normal skipCommitChecks=1`

**Comment by amazy** [comment]
Thanks for the report.  

However, I have to tell you that I have no idea when I'll look into it since we do not have an ARM64 processor available at hand and ARM64 is not our top priority right now (and we are more than overloaded).  Sorry for the delay ....

**Comment by urosch** [comment]
Ok, thank you for a quick answer!

**Comment by jodogne** [comment]
Also, don't hesitate to rebuild Orthanc from sources, instead of using this "orthanc-builder" environment. Raspberry is supported when building from source. Furthermore, Raspbian packages deriving from the official Debian packages are readily available: http://archive.raspbian.org/raspbian/pool/main/o/orthanc/
